# Development profile configuration
quarkus.profile=dev

# Logging - Development
quarkus.log.level=INFO
quarkus.log.category."com.stibodx".level=DEBUG
quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.type.descriptor.sql.BasicBinder".level=TRACE

# Database logging
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true

# Swagger UI always included
quarkus.swagger-ui.always-include=true

# HTTP configuration
quarkus.http.port=8080

# Hot reload
quarkus.live-reload.instrumentation=true

