quarkus.application.name=user-service
quarkus.application.version=1.0.0

# HTTP Configuration
quarkus.http.port=8080

# OpenAPI / Swagger UI Configuration
quarkus.swagger-ui.always-include=true

# Database Configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=stibo_user
quarkus.datasource.password=stibo_password
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/stibodx_db
quarkus.datasource.jdbc.max-size=20

# Hibernate Configuration
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.log.category."org.hibernate.tool.schema".level=DEBUG
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.sql-load-script=import.sql

# Logging Configuration
quarkus.log.level=INFO

mp.openapi.extensions.smallrye.operationIdStrategy=METHOD
quarkus.api.token=token-123
